### ISSUE TITLE
Problems installing blackboxoptim in Windows: URGENT SUGGESTIONS NEEDED

### ISSUE THREAD

**Issue by ajaykumar0712** [robertfeldt/BlackBoxOptim.jl#39] opened 2015-11-21 19:06 UTC
Hi everyone

I have tried installing blackboxoptim on Windows but I am having some trouble

I followed the instructions as stated but this is the message I get

```
: Cloning BlackBoxOptim from https://github.com/robertfeldt/BlackBoxOptim.jl
INFO: Computing changes...
INFO: No packages to install, update or remove
```

When I write usinig BlackBoxOptim
and I give it my function i get the message
```bboptimize not defined```

What should be my next steps?

**Comment by robertfeldt** [comment] 2015-11-22 18:47
Thanks for your feedback. This sounds strange indeed. I'm on Mac but tried these and things look ok both if installed as standard package and if I clone the git:

```
feldt:~/feldt/research/students/joakim_pernstal/papers/scream$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0 (2015-10-08 06:20 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  x86_64-apple-darwin15.0.0

julia> Pkg.rm("BlackBoxOptim")
INFO: Removing BlackBoxOptim v0.1.3
INFO: Package database updated

julia> using BlackBoxOptim
ERROR: ArgumentError: BlackBoxOptim not found in path
 in require at /usr/local/Cellar/julia/0.4.0/lib/julia/sys.dylib

julia> Pkg.add("BlackBoxOptim")
INFO: Installing BlackBoxOptim v0.1.3
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of BlackBoxOptim
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> using BlackBoxOptim
INFO: Precompiling module BlackBoxOptim...

julia> function rosenbrock2d(x)
         return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
       end
rosenbrock2d (generic function with 1 method)

julia> bboptimize(rosenbrock2d; SearchRange = (-5.0, 5.0), NumDimensions = 2);
Starting optimization with optimizer BlackBoxOptim.DiffEvoOpt{BlackBoxOptim.FitPopulation{Float64},BlackBoxOptim.RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps

Optimization stopped after 10001 steps and 0.04692196846008301 seconds
Termination reason: Max number of steps (10000) reached
Steps per second = 213141.10060211885
Function evals per second = 215485.41827697467
Improvements/step = 0.2082
Total function evaluations = 10111


Best candidate found: [1.000000000000365,0.9999999999998728]

Fitness: 7.3632e-23

julia> Pkg.rm("BlackBoxOptim")
INFO: Removing BlackBoxOptim v0.1.3
INFO: Package database updated

julia> Pkg.clone("https://github.com/robertfeldt/BlackBoxOptim.jl")
INFO: Cloning BlackBoxOptim from https://github.com/robertfeldt/BlackBoxOptim.jl
INFO: Computing changes...
INFO: No packages to install, update or remove
INFO: Package database updated

julia> using BlackBoxOptim

julia> bboptimize(rosenbrock2d; SearchRange = (-5.0, 5.0), NumDimensions = 2);
Starting optimization with optimizer BlackBoxOptim.DiffEvoOpt{BlackBoxOptim.FitPopulation{Float64},BlackBoxOptim.RadiusLimitedSelector,BlackBoxOptim.AdaptiveDiffEvoRandBin{3},BlackBoxOptim.RandomBound{BlackBoxOptim.RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps

Optimization stopped after 10001 steps and 0.05088496208190918 seconds
Termination reason: Max number of steps (10000) reached
Steps per second = 196541.36685611474
Function evals per second = 199528.49691932136
Improvements/step = 0.2027
Total function evaluations = 10153


Best candidate found: [0.9999999999999366,1.000000000000417]

Fitness: 2.95745e-23
```

Please try the same on your Windows machine and copy the responses back here, please, and we'll try to help you. Can you install other packages and run them?

**Comment by ajaykumar0712** [comment] 2015-11-22 19:05
Thank you for your suggestions

I tried again but I still see no results

```
![julia_optim_issue](https://cloud.githubusercontent.com/assets/12117141/11325685/eadfebfa-9121-11e5-9cb1-2a75c1d0377a.png)
```
I even went to C:\Users\Ajay\Julia and tried to physically delete the package 
But I still get errors

This has happened previously too with a few Julia packages.
I hope ditching windows is not the solution.

**Comment by ajaykumar0712** [comment] 2015-11-22 19:06
My apologies
i didn't attach the file properly

![julia_optim_issue](https://cloud.githubusercontent.com/assets/12117141/11325697/32b1e780-9122-11e5-8cdd-231156f5ba55.png)

**Comment by robertfeldt** [comment] 2015-11-22 19:09
It seems you are on Julia 0.3. We are changing to make 0.4 a requirement. Can you try on 0.4 also or do you need this to work on 0.3? Long-term we will only support 0.4.

**Comment by robertfeldt** [comment] 2015-11-22 19:13
I tried it on Julia 0.3.11 on my Mac and things still work even though there is a warning:

```
feldt:~/shared/dagstuhl/dagstuhl-bse/proposal$ julia03
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.11 (2015-07-27 06:18 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.rm("BlackBoxOptim")
INFO: Nothing to be done

julia> Pkg.add("BlackBoxOptim")
WARNING: julia is fixed at 0.3.11 conflicting with requirement for autotest: [0.4.0,∞)
INFO: Installing BlackBoxOptim v0.0.1
INFO: Removing Autoreload v0.2.0
INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of BlackBoxOptim
INFO: Use `Pkg.update()` to get the latest versions of your packages

julia> using BlackBoxOptim

julia> function rosenbrock2d(x)
                return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
              end
rosenbrock2d (generic function with 1 method)

julia> bboptimize(rosenbrock2d; SearchRange = (-5.0, 5.0), NumDimensions = 2);
Starting optimization with optimizer DiffEvoOpt{FitPopulation{Float64},RadiusLimitedSelector,AdaptiveDiffEvoRandBin{3},RandomBound{RangePerDimSearchSpace}}
0.00 secs, 0 evals, 0 steps

Optimization stopped after 10001 steps and 0.392657995223999 seconds
Termination reason: Max number of steps (10000) reached
Steps per second = 25470.002194389916
Function evals per second = 25714.48976669883
Improvements/step = 0.202
Total function evaluations = 10097


Best candidate found: [0.9999999999935679,0.99999999998812]

Fitness: 1.38217e-22
```

So it seems more likely that Julia is not setup properly on your Windows machine. Unfortunately I do not have a Windows machine to test on. Can you try to install some other packages and see if you get similar problems with them?

**Comment by ajaykumar0712** [comment] 2015-11-22 19:15
Thanks again.
This has happened a few times in the past 
I think the problem is that Julia by default is saved to D:\Users\Ajay\AppData

This creates some problems. I am not a computer scientist.
But this is my guess

I did try changing the path and I made the necessary changes in LightTable too
But things mess up at times.

I will look into it
If I feel I can't do more I will duly inform you

**Comment by robertfeldt** [comment] 2015-11-22 19:16
Ok, please submit a new issue if you think the problem is with BlackBoxOptim. I'm closing this for now. You should probably ask on julia-users mailing list about Windows setup if things continue acting strange.

**Closed by robertfeldt** 2015-11-22 19:16 UTC
