### ISSUE TITLE
fix deprecated inner constructor syntax, require 0.6?

### ISSUE THREAD

**Issue by tpapp** [robertfeldt/BlackBoxOptim.jl#79] opened 2018-04-05 09:25 UTC
On both the latest tagged release and `master`, I get warnings like
```julia
WARNING: deprecated syntax "inner constructor DictChain(...) around /home/tamas/.julia/v0.6/BlackBoxOptim/src/parameters.jl:8".                                                                                      
Use "DictChain{K,V}(...) where {K,V}" instead.                                                                                                                                                                       
```
While #69 fixed a lot of things, it would be great to fix these too. My understanding is that this would imply `julia 0.6` in `REQUIRE`, but that may be reasonable with `v0.7` around the corner. Also, [FemtoCleaner](https://juliacomputing.com/blog/2017/08/17/femtocleaner.html) could perhaps fix these automatically?

**Comment by robertfeldt** [comment] 2018-04-05 15:04
Yes, these are disturbing. Since we kind of "missed" the transition to 0.6 and 0.7 is coming up my plan is to go straight for 0.7. But I have tried FemtoCleaner, if it is easy why not. I'll explore...

**Comment by tpapp** [comment] 2018-04-05 18:00
I think the best approach is to support two consecutive versions to avoid [upgrade deadlock](https://discourse.julialang.org/t/1-0-adoption-path/7922/39). I was just suggesting that `v0.5` is dropped, making way for `v0.7`. I don't think `v0.6` should be "skipped" in any sense, especially because the package is working fine on it as is. `Compat.jl` and a bit of work should support both `v0.6` and `v0.7` (and thus eventually `v1.0`) very smoothly.

**Comment by robertfeldt** [comment] 2018-04-07 14:02
Hmm, I tried to install and run FemtoCleaner locally (on both 0.6.2 and latest 0.7) (to understand what is happening) but it fails to compile CSTParser and then I cannot run cleanrepo:

```julia
julia> FemtoCleaner.cleanrepo
ERROR: UndefVarError: cleanrepo not defined
```

I guess I can run it via the github app/bot but I'd like to understand the changes it proposes. Any advice?

**Comment by robertfeldt** [comment] 2018-05-17 05:52
@tpapp this should now be fixed on latest master, please check if you still have problems. We might have some performance regressions to weed out but most of the deprecations should be gone. If not, get back to us.

**Closed by robertfeldt** 2018-05-17 05:52 UTC

**Comment by tpapp** [comment] 2018-05-25 09:08
@robertfeldt: Thanks for the fix, no more warnings now.
